- name: "Install Storage SIG Yum Repos"
  yum: >
   name="centos-release-gluster{{ gluster_version }}"
  tags:
    - glusterfs

- name: "Install GlusterFS"
  yum: >
   name={{ item }}
   state=present
   enablerepo=centos-gluster{{ gluster_version }}
   disablerepo=base
  with_items:
    - glusterfs
    - glusterfs-cli
    - glusterfs-server
    - glusterfs-fuse
    - glusterfs-geo-replication
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version|int <= 6
  tags:
    - glusterfs

- name: "Install GlusterFS"
  yum: >
   name={{ item }}
   state=present
   enablerepo=centos-gluster{{ gluster_version }}
  with_items:
    - glusterfs
    - glusterfs-cli
    - glusterfs-server
    - glusterfs-fuse
    - glusterfs-geo-replication
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version|int >= 7
  tags:
    - glusterfs
